name: ci
on:
  push:

env:
  CLANG_VERSION: "15.0.2"
  VERBOSE: 1

jobs:
  CI:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
        # - macos-10.15 for as it takes too long to catch available runner
        compiler:
          - clang-15.0.2
          - gcc-11
        generator:
          - "Ninja Multi-Config"
        build_type:
          - release

        exclude:
          # mingw is determined by this author to be too buggy to support
          - os: windows-2019
            compiler: gcc

        include:
          - os: windows-2019
            build_type: Release
            package_generator: ZIP

          - os: ubuntu-20.04
            build_type: Release
            package_generator: TAR
      
    steps:
      - name: Setup needed variables
        uses: actions/github-script@v6
        with: 
          script: |
            CMAKE_PRESET='${{matrix.compiler}}'
            echo "CMAKE_PRESET=${CMAKE_PRESET//-*}-${{matrix.build_type}}-mode" | tee -a $GITHUB_ENV
          
      - name: Check env
        run: |
          echo ${{env.CMAKE_PRESET}}
      
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{matrix.compiler}}
          cmake: true
          ninja: true
          clangtidy: ${{env.CLANG_VERSION}}

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure CMake
        run: |
          cmake --preset ${{env.CMAKE_PRESET}}

      - name: Build
        run: |
          cmake --build ./out/build/${{env.CMAKE_PRESET}}

      - name: Test
        working-directory: ./out/build/${{env.CMAKE_PRESET}}
        run: |
          ctest -C ${{matrix.build_type}}
          
      - name: CPack
        if: matrix.package_generator != ''
        working-directory: ./out/build/${{env.CMAKE_PRESET}}
        run: |
          cpack -C ${{matrix.build_type}} -G ${{matrix.package_generator}}
