name: ci
on:
  push:

env:
  VERBOSE: 1

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
        # - macos-10.15 for as it takes too long to catch available runner
        compiler:
          - clang-15.0.2
          - gcc-11
        generator:
          - "Ninja Multi-Config"
        build_type:
          - release

        exclude:
          # mingw is determined by this author to be too buggy to support
          - os: windows-2019
            compiler: gcc

        include:
          - os: windows-2019
            build_type: Release
            package_generator: ZIP

          - os: ubuntu-20.04
            build_type: Release
            package_generator: TAR
            
    env:
      CMAKE_PRESET: ${{matrix.compiler}}-${{matrix.build_type}}-mode
      
    steps:
      - name: Setup CMake preset env
        run: |
          CMAKE_PRESET=${{CMAKE_PRESET}}
          echo CMAKE_PRESET=${CMAKE_PRESET//-*} >> $GITHUB_ENV

      - uses: actions/checkout@v3
      
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}

      - name: Configure CMake
        run: |
          cmake --preset ${{env.PRESET}}

      - name: Build
        run: |
          cmake --build --preset ${{env.PRESET}}

      - name: Test
        working-directory: ./out/build/${{env.PRESET}}
        run: |
          ctest -C ${{matrix.build_type}}
          
      - name: CPack
        if: matrix.package_generator != ''
        working-directory: ./out/build/${{env.PRESET}}
        run: |
          cpack -C ${{matrix.build_type}} -G ${{matrix.package_generator}}
